# Generated by Django 5.1.1 on 2024-10-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='tag_category',
            field=models.CharField(choices=[('people', 'People'), ('nature', 'Nature'), ('food', 'Food'), ('animal', 'Animal'), ('lifestyle', 'Lifestyle')], default='people', max_length=100),
        ),
    ]
