# Generated by Django 5.1.1 on 2024-10-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_tag_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
